global using HotelManagement.WebApp.Enums;
global using HotelManagement.WebApp.Models;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using HotelManagement.WebApp.Repositories;
global using  HotelManagement.WebApp.ViewModels;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;